# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20161008_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='subcategory',
        ),
    ]
